//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="ServiceReference1.ZSDRFC_SKN_GET_PRODUCTOS")]
    public interface ZSDRFC_SKN_GET_PRODUCTOS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZSDRFC_SKN_GET_PRODUCTOS:ZSDRFC_SKN_GET_PR" +
            "ODUCTOSRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.ZSDRFC_SKN_GET_PRODUCTOSResponse1> ZSDRFC_SKN_GET_PRODUCTOSAsync(ServiceReference1.ZSDRFC_SKN_GET_PRODUCTOSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSDRFC_SKN_GET_PRODUCTOS1
    {
        
        private ZSDT_MAEMAT00[] eT_PROD_GENERALField;
        
        private BAPIRETURN[] eT_RETURNField;
        
        private RSSELECT[] iT_FILTROSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSDT_MAEMAT00[] ET_PROD_GENERAL
        {
            get
            {
                return this.eT_PROD_GENERALField;
            }
            set
            {
                this.eT_PROD_GENERALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPIRETURN[] ET_RETURN
        {
            get
            {
                return this.eT_RETURNField;
            }
            set
            {
                this.eT_RETURNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RSSELECT[] IT_FILTROS
        {
            get
            {
                return this.iT_FILTROSField;
            }
            set
            {
                this.iT_FILTROSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSDT_MAEMAT00
    {
        
        private string zSD_CMATERField;
        
        private string zSD_CORVTAField;
        
        private string zSD_CCADISField;
        
        private string zSD_CSECTOField;
        
        private string zSD_DCORTAField;
        
        private string zSD_DLARGAField;
        
        private decimal zSD_PNETOField;
        
        private decimal zSD_PBRUTOField;
        
        private string zSD_CUNMPEField;
        
        private string zSD_CUNMBAField;
        
        private string zSD_CUNMVTField;
        
        private decimal zSD_NFUVTAField;
        
        private string zSD_CTPMATField;
        
        private string zSD_CJERARField;
        
        private string zSD_CGRMATField;
        
        private string zSD_CFAMMTField;
        
        private string zSD_CMARCAField;
        
        private string zSD_CCATEGField;
        
        private string zSD_CMRZTEField;
        
        private string zSD_CREGIMField;
        
        private byte zSD_QMINVTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ZSD_CMATER
        {
            get
            {
                return this.zSD_CMATERField;
            }
            set
            {
                this.zSD_CMATERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ZSD_CORVTA
        {
            get
            {
                return this.zSD_CORVTAField;
            }
            set
            {
                this.zSD_CORVTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ZSD_CCADIS
        {
            get
            {
                return this.zSD_CCADISField;
            }
            set
            {
                this.zSD_CCADISField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ZSD_CSECTO
        {
            get
            {
                return this.zSD_CSECTOField;
            }
            set
            {
                this.zSD_CSECTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ZSD_DCORTA
        {
            get
            {
                return this.zSD_DCORTAField;
            }
            set
            {
                this.zSD_DCORTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ZSD_DLARGA
        {
            get
            {
                return this.zSD_DLARGAField;
            }
            set
            {
                this.zSD_DLARGAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal ZSD_PNETO
        {
            get
            {
                return this.zSD_PNETOField;
            }
            set
            {
                this.zSD_PNETOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal ZSD_PBRUTO
        {
            get
            {
                return this.zSD_PBRUTOField;
            }
            set
            {
                this.zSD_PBRUTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string ZSD_CUNMPE
        {
            get
            {
                return this.zSD_CUNMPEField;
            }
            set
            {
                this.zSD_CUNMPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ZSD_CUNMBA
        {
            get
            {
                return this.zSD_CUNMBAField;
            }
            set
            {
                this.zSD_CUNMBAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ZSD_CUNMVT
        {
            get
            {
                return this.zSD_CUNMVTField;
            }
            set
            {
                this.zSD_CUNMVTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal ZSD_NFUVTA
        {
            get
            {
                return this.zSD_NFUVTAField;
            }
            set
            {
                this.zSD_NFUVTAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string ZSD_CTPMAT
        {
            get
            {
                return this.zSD_CTPMATField;
            }
            set
            {
                this.zSD_CTPMATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string ZSD_CJERAR
        {
            get
            {
                return this.zSD_CJERARField;
            }
            set
            {
                this.zSD_CJERARField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string ZSD_CGRMAT
        {
            get
            {
                return this.zSD_CGRMATField;
            }
            set
            {
                this.zSD_CGRMATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string ZSD_CFAMMT
        {
            get
            {
                return this.zSD_CFAMMTField;
            }
            set
            {
                this.zSD_CFAMMTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string ZSD_CMARCA
        {
            get
            {
                return this.zSD_CMARCAField;
            }
            set
            {
                this.zSD_CMARCAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string ZSD_CCATEG
        {
            get
            {
                return this.zSD_CCATEGField;
            }
            set
            {
                this.zSD_CCATEGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string ZSD_CMRZTE
        {
            get
            {
                return this.zSD_CMRZTEField;
            }
            set
            {
                this.zSD_CMRZTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string ZSD_CREGIM
        {
            get
            {
                return this.zSD_CREGIMField;
            }
            set
            {
                this.zSD_CREGIMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public byte ZSD_QMINVT
        {
            get
            {
                return this.zSD_QMINVTField;
            }
            set
            {
                this.zSD_QMINVTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class RSSELECT
    {
        
        private string fIELDNMField;
        
        private string sIGNField;
        
        private string oPTIONField;
        
        private string lOWField;
        
        private string hIGHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FIELDNM
        {
            get
            {
                return this.fIELDNMField;
            }
            set
            {
                this.fIELDNMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SIGN
        {
            get
            {
                return this.sIGNField;
            }
            set
            {
                this.sIGNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string OPTION
        {
            get
            {
                return this.oPTIONField;
            }
            set
            {
                this.oPTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string LOW
        {
            get
            {
                return this.lOWField;
            }
            set
            {
                this.lOWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string HIGH
        {
            get
            {
                return this.hIGHField;
            }
            set
            {
                this.hIGHField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPIRETURN
    {
        
        private string tYPEField;
        
        private string cODEField;
        
        private string mESSAGEField;
        
        private string lOG_NOField;
        
        private string lOG_MSG_NOField;
        
        private string mESSAGE_V1Field;
        
        private string mESSAGE_V2Field;
        
        private string mESSAGE_V3Field;
        
        private string mESSAGE_V4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE
        {
            get
            {
                return this.tYPEField;
            }
            set
            {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CODE
        {
            get
            {
                return this.cODEField;
            }
            set
            {
                this.cODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MESSAGE
        {
            get
            {
                return this.mESSAGEField;
            }
            set
            {
                this.mESSAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string LOG_NO
        {
            get
            {
                return this.lOG_NOField;
            }
            set
            {
                this.lOG_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LOG_MSG_NO
        {
            get
            {
                return this.lOG_MSG_NOField;
            }
            set
            {
                this.lOG_MSG_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string MESSAGE_V1
        {
            get
            {
                return this.mESSAGE_V1Field;
            }
            set
            {
                this.mESSAGE_V1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MESSAGE_V2
        {
            get
            {
                return this.mESSAGE_V2Field;
            }
            set
            {
                this.mESSAGE_V2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MESSAGE_V3
        {
            get
            {
                return this.mESSAGE_V3Field;
            }
            set
            {
                this.mESSAGE_V3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MESSAGE_V4
        {
            get
            {
                return this.mESSAGE_V4Field;
            }
            set
            {
                this.mESSAGE_V4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZSDRFC_SKN_GET_PRODUCTOSResponse
    {
        
        private ZSDT_MAEMAT00[] eT_PROD_GENERALField;
        
        private BAPIRETURN[] eT_RETURNField;
        
        private RSSELECT[] iT_FILTROSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZSDT_MAEMAT00[] ET_PROD_GENERAL
        {
            get
            {
                return this.eT_PROD_GENERALField;
            }
            set
            {
                this.eT_PROD_GENERALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPIRETURN[] ET_RETURN
        {
            get
            {
                return this.eT_RETURNField;
            }
            set
            {
                this.eT_RETURNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RSSELECT[] IT_FILTROS
        {
            get
            {
                return this.iT_FILTROSField;
            }
            set
            {
                this.iT_FILTROSField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZSDRFC_SKN_GET_PRODUCTOSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public ServiceReference1.ZSDRFC_SKN_GET_PRODUCTOS ZSDRFC_SKN_GET_PRODUCTOS;
        
        public ZSDRFC_SKN_GET_PRODUCTOSRequest()
        {
        }
        
        public ZSDRFC_SKN_GET_PRODUCTOSRequest(ServiceReference1.ZSDRFC_SKN_GET_PRODUCTOS ZSDRFC_SKN_GET_PRODUCTOS)
        {
            this.ZSDRFC_SKN_GET_PRODUCTOS = ZSDRFC_SKN_GET_PRODUCTOS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZSDRFC_SKN_GET_PRODUCTOSResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public ServiceReference1.ZSDRFC_SKN_GET_PRODUCTOSResponse ZSDRFC_SKN_GET_PRODUCTOSResponse;
        
        public ZSDRFC_SKN_GET_PRODUCTOSResponse1()
        {
        }
        
        public ZSDRFC_SKN_GET_PRODUCTOSResponse1(ServiceReference1.ZSDRFC_SKN_GET_PRODUCTOSResponse ZSDRFC_SKN_GET_PRODUCTOSResponse)
        {
            this.ZSDRFC_SKN_GET_PRODUCTOSResponse = ZSDRFC_SKN_GET_PRODUCTOSResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ZSDRFC_SKN_GET_PRODUCTOSChannel : ServiceReference1.ZSDRFC_SKN_GET_PRODUCTOS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ZSDRFC_SKN_GET_PRODUCTOSClient : System.ServiceModel.ClientBase<ServiceReference1.ZSDRFC_SKN_GET_PRODUCTOS>, ServiceReference1.ZSDRFC_SKN_GET_PRODUCTOS
    {
        
        public ZSDRFC_SKN_GET_PRODUCTOSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.ZSDRFC_SKN_GET_PRODUCTOSResponse1> ServiceReference1.ZSDRFC_SKN_GET_PRODUCTOS.ZSDRFC_SKN_GET_PRODUCTOSAsync(ServiceReference1.ZSDRFC_SKN_GET_PRODUCTOSRequest request)
        {
            return base.Channel.ZSDRFC_SKN_GET_PRODUCTOSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ZSDRFC_SKN_GET_PRODUCTOSResponse1> ZSDRFC_SKN_GET_PRODUCTOSAsync(ServiceReference1.ZSDRFC_SKN_GET_PRODUCTOS ZSDRFC_SKN_GET_PRODUCTOS)
        {
            ServiceReference1.ZSDRFC_SKN_GET_PRODUCTOSRequest inValue = new ServiceReference1.ZSDRFC_SKN_GET_PRODUCTOSRequest();
            inValue.ZSDRFC_SKN_GET_PRODUCTOS = ZSDRFC_SKN_GET_PRODUCTOS;
            return ((ServiceReference1.ZSDRFC_SKN_GET_PRODUCTOS)(this)).ZSDRFC_SKN_GET_PRODUCTOSAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
